### ISSUE TITLE
Missing _deploy folder

### ISSUE THREAD

**Issue by AlexVPopov** [imathis/octopress#1344]
This is the repo of my Octopress blog on GitHub pages: https://github.com/AlexVPopov/alexvpopov.github.io

When I clone the repo on another machine, run rake generate and then rake deploy, I get this message:

> ## Deploying branch to Github Pages 
> ## Pulling any updates from Github Pages 
> cd _deploy
> rake aborted!
> No such file or directory - _deploy
> 
> Tasks: TOP => deploy
> (See full trace by running task with --trace)

What should be done in this situation?

**Comment by justin808** [comment]
I get a similar message for a correct deploy. This looks like an error, but there is no error. The deployment still works. Any ideas?

```
## Deploying branch to Github Pages
## Pulling any updates from Github Pages
cd _deploy
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```

**Comment by maacl** [comment]
I also get this error.

**Comment by therealmarv** [comment]
I also got that error. It seems `rake deploy` does a pull request before pushing. Because normally you don't edit the deployed changes directly and you're working alone on your blog (it will fail if you working with 2+ people on your blog) the push at the end will just work.

To remove this warning message:

Either do once:

```
cd _deploy
git branch --set-upstream-to=origin/master master
```

---

Or **much better** patch the Rakefile yourself. In my Rakefile it is in line 255:

```
  cd "#{deploy_dir}" do 
    system "git pull"
  end
```

and replace the `system` command with:

```
  cd "#{deploy_dir}" do 
    system "git pull origin #{deploy_branch}"
  end
```
