### ISSUE TITLE
index.html parse error 

### ISSUE THREAD

**Issue by haoweishow** [imathis/octopress#1662]
* preview on local machine
```
rake preview
```
* the index.html file error
there is an error closed flag ,like the fellow,error end flag: & # 8211;
```
public\index.html

<!--
<link href="//fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
&#8211;>
```
* the browser can't display the posts,the index page is empty

**Comment by gauthma** [comment]
I can't believe this bug as yet to be addressed. I just updates octopress, and this happens. As far as I can see, the problem happens when commenting out tags. E.g.

```
<!-- <script></script> -->
```

Is transformed into

```
<!-- <script></script> &#8211;>
```

And when previewing in the browser only a blank page is shown. I think this should, at least, warrant a comment from the devs (even if only to say that why it hasn't been fixed, or if won't be fixed and why, or... something!)

**Comment by imathis** [comment]
This is your markdown processor replacing the dashes with an emdash. This is not something that Octopress is causing.
