### ISSUE TITLE
New Octopress release date?

### ISSUE THREAD

**Issue by maxhm10** [imathis/octopress#1726]
I'm thinking of creating some screencast material of this. So I was just wondering if you guys think it's a good idea, given the latest blog post. When do you plan to launch that?

**Comment by imathis** [comment]
That's awesome! I would definitely hold off until Octopress 3.0 is released. Since I do this project in my free time, I can't give a reliable ETA. Almost everything is done for the release, I'm just working on the new documentation site and finishing up the initial release theme. If you look at my GitHub punch card, you can see I've been working on this every day and night for the past 86 days straight. When it's ready I will make some noise.

I'm going to go ahead and close this since it isn't technically an issue. Feel free to continue discussion if you like.
