### ISSUE TITLE
Add support for 'Juvia'

### ISSUE THREAD

**Issue by lgp171188** [imathis/octopress#513]
Juvia(github.com/phusion/juvia) is an open-source commenting system that can be self-hosted. Would love to have support for that in Octopress. Can help with it.

**Comment by P3lUZa** [comment]
Any updates?

**Comment by imathis** [comment]
On the repo description it says "CURRENTLY UNMAINTAINED". I don't have a lot of incentive to spend time adding this if the developers have abandoned it.

**Comment by P3lUZa** [comment]
At least, can you add support for Isso, there must be an easy way. Look this implementation on Jekyll https://blog.altimos.de/2013/11/jekyll-and-isso/    .... Should I open a new Issue?

**Comment by P3lUZa** [comment]
And i forgot to say that Isso has an active development https://github.com/posativ/isso

**Comment by imathis** [comment]
It looks nice enough, but in order to properly test this it's going to take a lot of work. I'm not going to add this to Octopress 2.x. I'm about to make some [big changes](http://octopress.org/2015/01/15/octopress-3.0-is-coming/) and I don't really want to spend time working on this codebase anymore. If enough people are interested and if someone can set up a server for me to try, I'll see about adding support, or helping someone build their own plugin for Octopress 3.
